version: "3"
services:

  redis:
    image: redis
    ports:
      - "127.0.0.1:16379:6379"

  index:
    image: quay.io/acoustid/acoustid-index:master
    ports:
      - "127.0.0.1:16080:6080"

  postgres:
    image: quay.io/acoustid/postgresql:master
    command: ["-c", "max_connections=100", "-c", "max_prepared_transactions=110"]
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - ./admin/ci/create_db.sql:/docker-entrypoint-initdb.d/10_create_db.sql
    environment:
      POSTGRES_USER: acoustid
      POSTGRES_PASSWORD: acoustid
      POSTGRES_DB: postgres
